### ISSUE TITLE
Onion site redirects to clearnet website.

### ISSUE THREAD

**Issue by Vepnar** [CTemplar/webclient#1557]
### Your environment

Browser: Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)
Operating system: x86_64 Linux

### Steps to reproduce

1. Open the onion website `http://ctemplarpizuduxk3fkwrieizstx33kg5chlvrh37nz73pv5smsvl6ad.onion/`
2. Press the login button (Person with lock)
3. Get redirected to the clearnet version of the website `https://mail.ctemplar.com/mail/inbox/page/1`

### Expected behavior

I expect to get redirected to the onion version of the mail client.

### Actual behavior

I get redirected to the clearnet version of the mail client.

**Comment by The-Hidden-Hand** [comment]
@Vepnar 
We had to disable the Onion address because the Tor Browser is having recurring issues with the CORS as it is sending `null` in the Origin header of the request and it fails the check. The issues is recurring on their side and we have notified their development team a month ago. Unfortunately we cannot do anything at this point. We also tried to accept `null` string as CORS value as temporal workaround but the browser fails.

Related:
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/32865
