### ISSUE TITLE
Issue with keyboard shortcuts 

### ISSUE THREAD

**Issue by omridevk** [CTemplar/webclient#452]
Hi, I am the maintainer of ng-keyboard-shortcuts repo, I was wondering what is holding you back from using the repo:
https://github.com/CTemplar/webclient/blob/264c47e1f5e4e44d5c14148f1ab4f4b092ff6580/src/app/mail/mail.component.html#L21

I see you have a comment saying "wait until bugs are fixed", I was wondering if those are bugs in my library, if so, please let me know, I will do my best to address them as soon as possible.

**Comment by atifsaddique211f** [comment]
Hi @omridevk 
Thank you for reaching out to us.
Actually there were some issues, some users reported that when they close their email compose editor, it automatically take them to archive folder.
We use command `g + i` to go to archive folder, I have disabled keys usaged when compose editor is opened, so user shouldn't be facing this issue.
I was not able to reproduce this issue on my machine, neither our testing person.
We are currently busy on other critical tasks and will get back to shortcuts in few weeks.
From current situation, I can't really say if the issue is with the library or with our current implementation.

**Comment by omridevk** [comment]
Thanks for the quick response :)
No problem, If you do find it is an issue with my library, please feel free to open a issue on github or reach me directly at my email if you require any assistance. 
Have a wonderful week :)
