### ISSUE TITLE
Site displays blank page on Tor Browser with Security Slider on Safest

### ISSUE THREAD

**Issue by Zenithium** [CTemplar/webclient#518]
**Describe the bug**
Site is not viewable on Tor Browser with Security Slider set to Safest

**To Reproduce**
1. Open Tor Browser
2. Click on shield icon on toolbar (Security Level)
3. Click Advanced Security Settings
4. Select "Safest" option
5. Go to http://ctemplarpizuduxk3fkwrieizstx33kg5chlvrh37nz73pv5smsvl6ad.onion/

**Expected behavior**
Site is browsable with basic functionality 

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Tor Browser
 - Version 9.0.5

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
AFAIK it will not work because Tor on Safest mode blocks JS completely and if the website needs it to work you won't be able to use it, try accessing the new Reddit and/or some other website while on safest and you'll see it is all broken.

Regarding the use of Tor on Safest mode, from Matt Traudt's blog:

>Disabling JavaScript / setting the security slider to its highest setting
>----
>This is unnecessary for the majority of adversary models and will make the web significantly less usable.
>
>The only people who have had significant JavaScript exploits used against them in Tor Browser were pedophiles using Windows. This suggests to me (and security experts in general, AKA not people that read "tech news" and parrot everything they read) that these exploits are rare, expensive, and hard to replace. Thus they aren't going to be used against random people because the risk of the exploit being discovered and fixed is too great.
>
>Setting the security slider to its highest setting does remove JavaScript as a possible attack vector. So as long as you set it there consciously, are aware much of the web may break, I support your choice to disable it. I especially support it if you have legitimate concerns that JavaScript exploits may be used against you, not just dumb paranoia.

**Comment by zenithium** [comment]
@5a384507-18ce-417c-bb55-d4dfcc8883fe I am aware that this is a JS issue as indirectly stated in #519 and I am also aware of what using the slider on highest entails, As I stated in the issue I disagree that the site **needs** it to work as static content could be displayed normally. In this issue I explicitly said **basic functionality** and not a fully functional site or anything of the sort. I simply consider showing a blank page just because JS is disabled unacceptable. I can not even get to the privacy policy to decide if I want to trust the site enough to enable JS.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
I don't want to create a discussion here, since this should be used to improve the website and fix bugs, but I think that if you would understand Traudt's extract then you wouldn't be using Tor on Safest, unless you are Snowden's cousin, of course.
I'm pretty sure that CTemplar requires JS to provide a more modern experience that can attract a broader audience, these people need to make a living, too, they can't live only from Tor users.

I think Autistici/Inventati, RiseUp, Disroot, Dismail, Systemli and NixNet mail can be more or less used without JS, but I might be wrong.

**Comment by Godfry** [comment]
You both have very good comments.  Before I talk about Javascripts I want to let you know that we have changed our policy and will never use a CDN.  We will post information about it this week.

Javascript is often used maliciously to harm peoples privacy.  However JavaScript is required to perform the encryption/decryption.  So we asked our self this question... "How do we use Javascript but give people strong assurance that it is not being used against them maliciously?  Here is the solution we arrived at: 

We have open source code, anyone can review our code to gain assurance that there is nothing in our code to harm you.  Many services have open source code but there is still a problem with this.  How can a user be certain they are served the same code to their browser that is available in github?  
1. You can visit our service directly using the code inside github using "https://gh.ctemplar.com".  
2. You can perform a checksum to check all of the code in your browser against the code in github.  If one letter is different then the code in your browser then your visit terminates for your safety.  Performing a checksum takes about 1-2 min to do the first time, then it takes 10-20 seconds in the future.  Later this year we will have a much faster method of doing this. [You can read more about it on our blog.](https://ctemplar.com/ctemplar-checksum-implementation/)

CTemplar's solutions to protecting users from malicious javascripts have not been applied to any E2EE service before. We take pride in applying these solutions to the JavaScript problem. However there are many excellent services available that @5a384507-18ce-417c-bb55-d4dfcc8883fe  mentioned above. And the most important thing is not which service you use, but instead that you protecting yourself from the abusive practices of invasive governments and corporations.  

Thank you for your comments.  They are gifts that allow us to improve or explain things better on our site. 

Kind Regards to you,

**Comment by zenithium** [comment]
First of all, thank you @Godfry for being so involved in the community and listening to user feedback, I sadly don't see that often with project owners. I'm a big fan of CTemplar and I think you have the best ToS and Privacy Policy out of any email provider currently, so I definitely want to do what I can to see you improve. Regarding the encryption, from what I understand it is only necessary on the login page and while the user is in their inbox so their emails can be decrypted, so I think it's very doable to make the base site (HOME, ABOUT, SECURITY, PRICING, BLOG, SUPPORT) navigable without JavaScript as it would be pleasant for potential users of CTempar to look around the site while feeling safe with no JS. As I mentioned in my post above users cannot currently browse the site at all, look at the Privacy Policy, etc. they cannot know anything about CTemplar without enabling JavaScript first. This requires the users to trust CTemplar first and then afterwards see that it is safe.

**Comment by The-Hidden-Hand** [comment]
Being built on Angular the webclient needs javascript to run.
