### ISSUE TITLE
Cheap subscription

### ISSUE THREAD

**Issue by notramo** [CTemplar/webclient#576]
The entry level plan is **very** expensive. No other encrypted mail provider has such high prices.
I understand that more storage costs money to you. But there are features that **doesn't need more system resources**. There should be a basic plan for half € per month which would enable these features. For example, the dead man's timer doesn't need more system resources, so this should be available in the cheap plan. Subject encryption, and delayed delivery also. So if somebody has this cheap plan, it **wouldn't cost any money** to you but you would get a **little income**, and the users could afford it. This would be a **killer feature** too, because many users doesn't need more storage but want to use these features, and other encrypted mail providers doesn't have the "without-storage" cheap subscription. This would make CTemplar the cheapest provider for them.
This plan could be also granted to those who contribute with bug reports or translations, because it doesn't costs anything for you but would highly encourage people contributing.

**Comment by Godfry** [comment]
Thanks you for your comment.  First of all I thought I would reply to your comments

**Reply to your comments:** 

Some services are able to offer free email because they sell their users private information.  Other services discount their services using funds received global corporations or governments.  I have read corporate financial aid proposals and find them to be designed to abuse users privacy.  Other services use free code from services like rainloop.  They have no construction or maintenance costs so they can offer a cheap or free service.  

We are not trying to become the next Gmail, or Yahoo.  We aren’t going to use free software from others, and we will never accept Corporate or Government aid.  We are offering a niche email service for those who want a custom service, that is not subsidized by a Government or Global Corporation.  I have reviewed the company finances and we priced things at the level we need them to at to continue operations.  Some people get upset when they learn I’ve declined government aid proposals and corporate investment.  I tell them that the proposals were designed with the intent to abuse our user's privacy.  Then I direct those people to other services like Protonmail or Tutanota.  They are exceptional services, and all email services are soldiers who stand side by side in the war to protect privacy.  

When I designed the security features list, I used Lavabit as an example. They offered some security features for the paid accounts that were not available for free accounts. 

**Changes we'll make due to your comments:** 

- We’re going to review which security features are available to free accounts.  You made good points, we’ll review it again and likely make changes. 
- I think we can offer a discounted or free “Prime” account to contributors, charitable organizations. For example, you have reported bugs and I value the work you did to be higher than the price of a paid subscription.  

**Future Plans**

In the future, we plan to add some features and services at no added cost.  For example, we plan to add a ‘google drive’ type service, with End the End encryption, for no added cost to all paid accounts.  And this service will also be available to free accounts to a lesser degree.  

This industry is really difficult because I can't call a billion-dollar investment partner and ask for a few hundred thousand dollars for something.  This has to be able to support itself but people expect email to be free (gmail), or they expect it to be offered cheaply because they use government-subsidized email services as an example.  

I hope I did not come across as combative. The bottom line is you made some good points and we'll be reviewing things again.  And I also deeply appreciate your comments and input in Github.  Many of our best features have been suggested by people from the community like you.  

Kind Regards to you,

**Comment by notramo** [comment]
**What are CTemplar's offer for those who don't need more storage, only cool features?** (and don't want to pay or can't afford more storage)

There was a ProtonMail user in a chat room who wanted to have only more filters (no extra storage or other features), but this is available only with ProtonMail paid subscription. This would be one case when you could say "Come to CTemplar, and you can get filters for half an € per month without unnecessarily paying for unneeded storage" Currently, he continues using ProtonMail, because he have to buy storage too with either provider, and in this case ProtonMail is cheaper. In this case **you get nothing**, but if you had that plan, you would get half €.

I want to have delayed delivery, but not other features. I don't want to pay so much for this simple feature. I don't have other choice than remaining on free plan, and using CTemplar without this feature. So you don't have any income from me. If you had that plan, I would probably buy it, and you would get half  €. (Which is better than nothing.)

**What about splitting the plan on features/storage**
The **Basic** plan would cost half an € per month (making CTemplar the cheapest option, Tutanota has 1 €), but it wouldn't include more storage. This would **bring more users**, because no other provider has this subscription. You wouldn't have **less income**, because these users currently simply **don't use** CTemplar, or **don't pay anything**, because they rather remain on free plan than paying so much.
If somebody want to have more storage, they could add as much as they want for 1 €/GB/month.

This would be the most rational solution, let the users choose features, and pay for it. Imagine when you go to the shop:
"I want to buy 1kg of bread"
"Okay, but you have to buy 1l of milk, and some cheese and butter, and also some vegetables too"
"But I don't want those, only the bread"
"Sorry, you can't buy bread only, we have only this pack"
Would you buy the pack? Probably no. You would probably go home without bread. **Was it good for you (the customer)?** No. **Was it good for the shop manager?** No. **Did the shop manager earn more money than if they were offering single products instead of pack?** No, because customers don't buy it.

**Comment by the-hidden-hand** [comment]
Hello @notramo,

Thanks for your suggestions. We totally acknowledge and understand your point, and it will be discussed in the next evaluation round. Please don't expect this to happen immediately soon because we are on the track for releasing other exiciting changes and new features first.

Kind regards.

**Comment by Godfry** [comment]
@notramo Yea you have some really good points.  We'll have responses to this in the future.  You've been a great contributor here, email me, godfrey@Ctemplar.com, and I would love to repay the time you've put into this with a free prime subscription.
