### ISSUE TITLE
Error clicking outside encryption link

### ISSUE THREAD

**Issue by SecretestSquirrel** [CTemplar/webclient#864]
**Description**
Received encrypted email from Tutanota user. Opened in 2.5.3 AppImage, tried selecting hyperlink and received error message 
![IMG_20201122_074118_698](https://user-images.githubusercontent.com/74485231/99898243-e3e43600-2c97-11eb-9173-c29b71d20d76.jpg)

**Steps to reproduce the behavior**

1. Receive encrypted email from Tutanota
2. Click on hyperlink provided
3. See error

**Your expectation**
Open default browser and page specified by hyperlink

**Environment**

- OS: Ubuntu 18.04
- Device: Lenovo laptop
- Browser: Tried with Chromium Browser, Brave Browser, and Tor Browser set as default

**Screenshots**
Error message 
![IMG_20201122_074118_698](https://user-images.githubusercontent.com/74485231/99898319-6d940380-2c98-11eb-9936-976c1524e8af.jpg)
Email showing hyperlink 
![IMG_20201122_074621_714](https://user-images.githubusercontent.com/74485231/99898325-7c7ab600-2c98-11eb-9ab0-6f2d43368095.jpg)

**Comment by The-Hidden-Hand** [comment]
Thanks for reaching us! We are reviewing the desktop apps for solving some bugs like this that were reported recently. You can expect a solution in the next one or two releases.

**Comment by The-Hidden-Hand** [comment]
Dear @SecretestSquirrel,

We have solved the issue with links received on mails, and we are reviewing all other links from the interface. If you want to review, here is how you can build the dev version: https://github.com/CTemplar/webclient/tree/dev#build-cross-platform-electron-client

In any case, expect this being solved by next week with the version 2.5.6.

Thanks for getting in touch, please let us know if you find any other issue because we appreciate your feedback.
