### ISSUE TITLE
Use the 'toaster' notifications service for displaying errors

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#979]
### Expected behavior

Use the `toaster` notifications service for displaying any error or exception. This way users will know that an exception has happened and they will have an accurate error message without having to reproduce and/or have to open the JS console for future reporting. This will also replace all the console.log we have.

**Comment by happyman125** [comment]
@The-Hidden-Hand I think we shouldn't display error messages as toaster. 
For example, if error message is "can't be defined property of undefined", developers can understand and track issue but
users can't understand this and moreover, we shouldn't display such messages on production because users can think this service is not completed or have many issues.

**Comment by The-Hidden-Hand** [comment]
@happyman125 
The toaster will display nice messages, with or without error code, to identify the reason. The user knows something has happened instead of simply feeling some action doesn't trigger after an exception. For example, if a message cannot be decrypted, it won't keep spinning forever without notice (or just a 'key mismatch' error in the console).

There are some places using console.log and console.error pending from the other task we could start from.
