### ISSUE TITLE
Deleting the last message in a page raises an exception

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#987]
### Your environment

Firefox on Linux.

### Steps to reproduce

1. Open the last message in the pagination of the first page on a multipage folder.
2. Delete it.

### Expected behavior

It brings me to the next message as it does when deleting any other message.

### Actual behavior

It [raises an exception on Sentry](https://sentry.io/organizations/ctemplar/issues/2083998397/), and it brings me back to the folder.

**Comment by The-Hidden-Hand** [comment]
It also happens with the last message in a single page folder.

**Comment by happyman125** [comment]
@The-Hidden-Hand I need to discuss this task. When I check code, i found deleting feature on detail page is not right.
When delete message on detail page, if we want to display next message, we should call API and get next data because we get fixed number of messages with API call so if we delete message, we should get next message additionally.

When I check gmail, it always returns folder after deleted message. I think it is right way. how do you think?

**Comment by The-Hidden-Hand** [comment]
@happyman125 
Let's do it as you say.
